apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mozpac9ya-go
  janus-idp.io/tekton: mozpac9ya-go
  backstage.io/kubernetes-id: mozpac9ya-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mozpac9ya-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
